<style>
  #familyBody{
    height: calc(100% + 20px);
    width: calc(100% + 20px);
    margin: 0%;
    display: table;
    border-spacing: 10px;
    margin: -10px;
  }

  #familyAddressFormWrap_<?=$tabId?>{
    position: relative;
    margin: 0px;
    width: 100%;
    height: 100%;
  }

  .familylist_<?=$tabId?>{
    position: absolute;
    left: 0px;
    right: 0px;
    top: 0px;
    bottom: 0px;
    padding: 0px;
    margin: 0px;
  }

  .familylistWrap_<?=$tabId?>{
    top: 42px;
  }

  #familyAddressForm_<?=$tabId?>{
    position: absolute;
    left: 5px;
    top: 46px;
    width: calc(100% - 32px);
    background-color: #ddd;
    border-radius: 8px;
    border: 1px solid #666;
    padding: 10px;
    margin-right: 5px;
    text-align: center;
  }
  .addressFormWrap_<?=$tabId?>{
    max-width: 800px;
    text-align: center;
    margin-left: 50%;
    transform: translatex(-50%);
  }

  @media(max-width: 1199px) {
    .largeWindow{
      display: none;
    }
    .smallWindow{}
  }
  @media(min-width: 1200px) {
    .smallWindow{
      display: none;
    }
    .largeWindow{}
  }

  .w50{
    width: calc(50% - 24px);
  }
  .w150{
    min-width: max-content;
    max-width: 11%;
  }
  .w200{
    min-width: 100px;
    max-width: 200px;
    width: 100%;
  }
  .w30{
    width: 30%;
  }

  .familyDiv_<?=$tabId?>{
    position:relative;
    margin: 0px;
    height: 100%;

    padding:0px;
    background-color: #aaa;
    box-shadow: inset 0px 0px 5px #222;
    display: table-cell;
    overflow: hidden;
  }

  #familyFormWrap_<?=$tabId?>{
    display: table-cell;
    position: absolute;
    top: 10px;
    width: calc(70% - 20px);
    height: calc(100% - 20px);
  }

  .familyListHeader{
    position: absolute;
    left: 0px;
    right: 0px;
    top: 0px;
    background-color: #A2BCE8;
    box-shadow: inset 0px 5px 5px -5px #212, inset -5px 0px 5px -5px #222, inset 5px 0px 5px -5px #222, 0px 3px 3px -3px #222;
    text-align: center;
    padding-top: 10px;
    padding-bottom: 10px;
    font-size: 18px;
  }

  .memberName{
    cursor: pointer;
    margin: 5px 5px 0px 5px;
    background-color: #ddd;
    padding: 10px 20px;
    border: 1px solid#666;
    border-radius: 4px;
    font-size: 14px;
  }
</style>

<div id='familyBody'>
  <div id='familyDiv_<?=$tabId?>' class='w30 familyDiv_<?=$tabId?>'>
    <div class='familyListHeader'> Family Members </div>
    <div id='familyListWrap_<?=$tabId?>' class='familylistWrap_<?=$tabId?> familylist_<?=$tabId?>'>
      <ul id='familyList_<?=$tabId?>' class='familylist_<?=$tabId?>'>
        <li id='famHI_<?=$tabId?>' class='memberName' data-type='info'>Household Info</li>
        <li id='membAdd_<?=$tabId?>'  class='memberName' data-type='add'>Add New Member</li>
        <li class='memberName' data-type='member'>Jacob Chisholm</li>
        <li class='memberName' data-type='member'>Jacki Chisholm</li>
      </ul>
    </div>
  </div>

  <div id='familyFormWrap_<?=$tabId?>' class='familyDiv_<?=$tabId?>'>
    <div id='familyAddressFormWrap_<?=$tabId?>' class='table' style='display:none;'>
      <div class='familyListHeader'> Household Information </div>
      <form id='familyAddressForm_<?=$tabId?>'>
        <div id='addressFormWrap_<?=$tabId?>' class='addressFormWrap_<?=$tabId?>'>
          <div class='row ttl'> Address </div>
          <div class='row buttonRow'>
            <div class='buttonRowWrap'>
              <?= button($tabId,'Update Family', 'w50'); ?>
              <?= button($tabId,'Delete Family', 'w50'); ?>
            </div>
          </div>
          <div class='row'>
            <div class='cell lbl w150'> House Name: </div>
            <input class='cell intext w200' type='textbox' name='familyName' tabindex=1 />
            <div class='cell lbl w150'> City: </div>
            <input class='cell intext w200' type='textbox' name='city' tabindex=4 />
              <div class='cell lbl w150 largeWindow'> Phone 1: </div>
              <input class='cell intext w200 largeWindow' type='textbox' name='phone1' tabindex=7 />
          </div>
          <div class='row'>
            <div class='cell lbl w150'> Address 1: </div>
            <input class='cell intext w200' type='textbox' name='address1' tabindex=2 />
            <div class='cell lbl w150'> State: </div>
            <input class='cell intext w200' type='textbox' name='state' tabindex=5 />
            <div class='cell lbl w150 largeWindow'> Phone 2: </div>
            <input class='cell intext w200 largeWindow' type='textbox' name='phone2' tabindex=8 />
          </div>
          <div class='row'>
            <div class='cell lbl w150'> Address 2: </div>
            <input class='cell intext w200' type='textbox' name='address2' tabindex=3 />
            <div class='cell lbl w150'> Zip: </div>
            <input class='cell intext w200' type='textbox' name='zip' tabindex=6 />
          </div>
          <div class='row'>
            <div class='cell lbl w150 smallWindow'> Phone 1: </div>
            <input class='cell intext w200 smallWindow' type='textbox' name='phone1' tabindex=7 />
            <div class='cell lbl w150 smallWindow'> Phone 2: </div>
            <input class='cell intext w200 smallWindow' type='textbox' name='phone2' tabindex=8 />
          </div>
        </div>
      </form>
    </div>
    <div id='familyPersonForm_<?=$tabId?>' style='display:table;'>
      <div class='familyListHeader'> Person Information </div>
      <form id='familyAddressForm_<?=$tabId?>'>
        <div id='addressFormWrap_<?=$tabId?>' class='addressFormWrap_<?=$tabId?>'>
          <div class='row ttl'> Census </div>
          <div class='row buttonRow'>
            <div class='buttonRowWrap'>
              <?= button($tabId,'Update Person', 'w50'); ?>
              <?= button($tabId,'Delete Person', 'w50'); ?>
            </div>
          </div>
          <div class='row'>
            <div class='cell lbl w150'> First Name: </div>
            <input class='cell intext w200' type='textbox' name='familyName' tabindex=1 />
            <div class='cell lbl w150'> Middle Name: </div>
            <input class='cell intext w200' type='textbox' name='familyName' tabindex=1 />
            <div class='cell lbl w150'> Last Name: </div>
            <input class='cell intext w200' type='textbox' name='city' tabindex=4 />
          </div>
          <div class='row'>
            <div class='cell lbl w150'> Birthdate: </div>
            <input class='cell intext w200' type='textbox' name='address1' tabindex=2 />
          </div>
        </div>
      </form>
      <!-- <form id='familyAddressForm_<?=$tabId?>'>
        <div id='addressFormWrap_<?=$tabId?>' class='addressFormWrap_<?=$tabId?>'>
          <div class='row ttl'> Sacraments </div>
          <div class='row'>
            <div class='cell lbl w150'> Where: </div>
            <input class='cell intext w200' type='textbox' name='familyName' tabindex=1 />
            <div class='cell lbl w150'> When: </div>
            <input class='cell intext w200' type='textbox' name='familyName' tabindex=1 />
          </div>
          <div class='row'>
            <div class='cell lbl w150'> Documents: </div>
            <input class='cell intext w200' type='textbox' name='address1' tabindex=2 />
          </div>
        </div>
      </form> -->
    </div>
  </div>
</div>
