<?php loadCss(__DIR__."/security.css"); ?>
<div id="securityDiv_<?= $tabId ?>" class='securityDiv'>
  <form id='securityForm_<?= $tabId ?>' class='table'>
    <input type='hidden' name='userid' value='' />
    <input type='hidden' name='id' value='' />
    <div class='headTitle'> User Security </div>
    <div class='buttonRow'>
      <div class='buttonRowWrap'>
        <?= button($tabId,'Update', 'w33'); ?>
        <?= button($tabId,'Insert', 'w33'); ?>
        <?= button($tabId,'Delete', 'w33'); ?>
      </div>
    </div>
    <br>
      <div class='label'> Name: </div>
      <input class='readonly' type='textbox' name='name' readonly='true'/>
    <br>
      <div class='label'> Username: </div>
      <input type='textbox' name='username' />
    <br>
      <div class='label'> Password: </div>
      <input type='password' name='password' />
    <br>
      <div class='label'> Id: </div>
      <input class='readonly' type='textbox' name='ids' readonly='true' />
    <br>
      <div class='label'> Active: </div>
      <input type='checkbox' name='active' />
    <br><br>
    <div class='label'>Permission:</div>
    <div class='w25'> R </div>
    <div class='w25'> I </div>
    <div class='w25'> U </div>
    <div class='w25'> D </div>
    <?= $checks ?>
  </form>
</div>
